name: Deploy (dev.ibc.fun)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Pull latest 'main'
        run: git pull origin main
      - name: Fast forward 'main' → 'dev'
        run: git merge --ff-only origin/main
      - name: Push latest 'dev'
        run: git push --set-upstream origin dev
