name: Deploy (dev.ibc.fun)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fast-forward main -> dev
        run: |
          git checkout dev
          git merge --ff-only main
          git push --set-upstream origin dev
