name: Deploy (dev.ibc.fun)
on:
  pull_request:
    branches: [main]
    types: [closed]
  push:
    branches: [main]
  repository_dispatch:
    types: [deploy-dev]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev

      - id: pull-main
        name: Pull latest 'main'
        run: git pull origin main

      - id: diff-check
        name: Check if 'dev' is behind 'main'
        run: git diff --exit-code origin/main

      - id: fast-forward
        name: Fast forward 'main' → 'dev'
        run: git merge --ff-only origin/main

      - id: push-dev
        name: Push latest 'dev'
        run: git push --set-upstream origin dev
